### PR TITLE
Skip non-ascii encoded env variables

### PR DESCRIPTION
**Pull request by ryandub**
Using this with Celery, I ran into issues with non-ascii environment variables from Celery (not sure what these are), but they caused a huge issue. This may not be the best way to approach this problem - open to suggestions.

### CODE REVIEW

**Comment by glyph** [comment]
Hi @ryandub !

Sorry I wasn't paying much attention to this repo.  Can you include a test, by any chance?

Thanks!

**Comment by ryandub** [comment]
Thanks @glyph - I added some tests around the environment with ascii and non ascii characters. Let me know if that looks good for you!

**Comment by glyph** [comment]
@ryandub - looks like python 3.2 doesn't like it?  (an eminently reasonable solution to this would be "stop supporting 3.2" since almost nobody uses that version, but gotta make the travis check green ;-))

**Comment by ryandub** [comment]
Ah, thanks. My tests passed locally, but tox is not using 3.2. Will give it a few more kicks and figure out what I broke. :)

**Comment by glyph** [comment]
Just doing some project gardening and noticed this.  Ping?

**Pull request closed without merging**
